export default {
    toload: {
        load: "加载中",
        loading: "加载中..."
    },
    datatime: {
        cancel: "取消",
        confirm: "确定",
        year: "年",
        month: "月",
        days: "日",
        hour: "时",
        min: "分",
        second: "秒"
    },
    timePick: {
        hour: "时",
        min: "分",
    },
    delModel: {
        text: "确认将这个地址删除？",
        cancel: "取消",
        confirm: "确认"
    },
    laikepay: {
        paySuccess: "支付成功！",
        rechargeFail: "充值失败！",
        hint: "提示",
        payFail: "支付失败,查看订单详情",
        paying: "支付中...",
        pswdFail: "您输入密码错误,请重新输入",
        maxFail: "你输入的错误次数已达当日上限，请使用其它支付方式进行付款",
        networkError: "网络错误，请稍后再试",
        fullPswd: "请输入完整密码！",
        payFail1: "支付失败,订单已生成，可以在订单列表中查看",
        noAccess: "网络繁忙，支付失败  订单已生成，可以在订单列表中查看",
        mimaError: "密码错误次数达到上限上限，请明日再来"
    },
    laiketuiCommon: {
        noLogin: "未登录，请先登录",
        forFailure: "获取失败",
        iosFail: "ios暂不支持虚拟支付",
    },
    liveItem: {
        live: "直播",
        notBegun: "未开始",
        playback: "回放",
        liveNotStarted: "直播未开始"
    },
    lktauthorize: {
        welcome: "欢迎您的到来",
        authorized: "授权登录，获得完整购物体验.",
        cancel: "取消",
        authorization: "授权",
        pleaseLogin: "请登录！",
    },
    mpvuePicker: {
        cancel: "取消",
        confirm: "确定",
        hour: "时",
        min: "分"
    },
    paymodel2: {
        
    },
    skus: {
        kucun: "库存",
        num: "数量",
        confirm: "确认",
        chooseTips: "请先选择商品规格",
        maxNum: "数量已经达到上限了哦！",
        minNum: "数量已经减少到最低了哦！",
        stockTips: "库存不足，请选择其它!",
    },
    loadMore: {
        contentText: {
            contentdown: '上拉显示更多',
            contentrefresh: '正在加载...',
            contentnomore: '没有更多数据了'
        }
    },
    showLoading: {
        upLoading: "上传中...",
        waiting: "请稍后...",
        axiospaying: "正在请求支付...",
        paying: "正在支付...",
        loading: "加载中...",
        axiosing: "请求中...",
        paying1: "支付中...",
    },
    showModal: {
        hint: "提示",
        hint1: "温馨提示",
        mima: "请先设置支付密码",
        payFail: "支付失败,查看订单详情",
        nomima: "您的账号还未设置密码，是否前往设置？",
        loginNo: "获取登录通道失败！",
        noTel: "请先绑定手机号再提现！",
        submit: "是否提交修改？",
        payFail1: "支付失败",
        noCantuan: "无法继续参团,需要参加其它团吗?",
        payFail2: "支付失败，请重试",
        confirm: "确定",
        cancel: "取消",
        shareContent: "一起来用豪眼光吧！"
    },
    toasts: {
        copyText: {
            success: '复制成功'
        },
        request: {
            error: '请求出错'
        },
        landing: [
            "格式正确！",
            "用户名不能为空",
            "密码不能为空！",
            "请输入6-16位数密码（数字和字母组合）！",
            "请输入密码！",
            "请输入确认密码！",
            "两次输入不一致！",
            "请输入正确的手机号！"
        ],
        authorized: {
            refused: "授权拒绝",
            success: "授权成功",
            failure: "授权失败",
            reLoginFailed: "重新登陆失败",
            noUser: "用户不存在！",
            logonException: "登陆异常，请联系管理员！"
        },
        bidding: {
            copyOk: "复制分享链接成功！",
            copyFail: "复制分享链接失败！",
            payOk: "支付成功！",
            yjOk: "上交押金成功！",
            moneyOk: "请输入正确的金额",
            bidFailed: "出价失败",
			dada:"距离太远,无法配送"
        },
        distribution_center: {
            lkt_money: ["提现金额需大于", "元,请重新输入!", "提现金额不能大于总金额，请重新输入!"],
            lkt_bank: "银行卡号输入错误，请重新输入！",
            lkt_bank_p: ["请输入合法的银行卡号！", "银行卡号输入错误，请重新输入！"],
            lkt_getcode: "请输入正确的手机号码！",
            lkt_submit: ["提现申请成功！", "请先获取验证码！", "手机号码输入不一致,请确认后提交！", "请填写完整信息！"],
            lkt_saveimg: ["保存成功", "保存失败", "下载失败"]
        },
        goodsDetailed: {
            shareOk: "分享成功!",
            shareFail: "分享失败!",
            szOk: "收藏成功！",
            addOk: "添加成功，在购物车等您哦~",
            lqOk: "领取成功",
            kucun: "库存不足",
            choose: "请选择完整的商品规格！",
            shareWay: ["微信", "朋友圈", "二维码分享"]
        },
        groupDetailed: {
            shareOk: "分享成功!",
            shareFail: "分享失败!",
            gocantuan: ["活动已结束，无法购买！", "每位用户最多参团", "次！", "不能继续参加此商品的拼团！"],
            downEWM: ["保存图片成功", "保存图片失败"],
            reduce: ["请选择完整商品规格", "请选择完整拼团人数", "数量已经减少到最低了哦"],
            buy: ["活动已结束，无法购买", "活动暂未开始，无法购买", "每位用户最多能开", "个团", "不能继续开此商品的拼团"],
            confirm: ["库存不足", "请选择拼团人数", "请选择完整的商品规格"]
        },
        login: {
            fsOk: "发送成功",
            fsFail: "短信发送频率超限!",
            tel: "请输入手机号码!"
        },
        uploadPro: {
            setAttr: "请先完善以上的信息",
            changeActive: ["该商品有未完成的订单，无法修改活动类型", "该商品有参与插件活动，无法修改活动类型"],
            check: ["请填写核销地址", "请填写完整信息"],
            upOk: "上传成功",
            cbjFail: "售价低于成本价"
        },
        order: {
            send: "发货成功",
            confirm: ["该产品规格库存不足", "请选择完整的商品规格"],
            axios: ["此团已成功，请重新选择参团或开团", "此团已失败，请重新选择参团或开团", "等待发货", "超时关闭"],
            txfh: "已提醒卖家发货！",
            submit: ["您输入密码错误，请重试", "您输入密码错误，请明天再使用钱包支付", "请输入完整密码！", "你输入的错误次数已达当日上限，请使用其它支付方式进行付款"],
            payOk: "支付成功",
            choosePay: "请选择支付方式",
            yueFail: "余额不足，请选择其它支付方式",
            qxOk: "取消成功",
            yfh: "卖家已发货",
            delOk: "删除成功",
            submitTwo: ["拼团活动已经结束", "此商品秒杀数已达上限", "此秒杀商品已经超过秒杀时间", "参团数已达上限", "开团数已达上限", "不可重复参加此商品的团", "不可重复开此商品的团",
                "你已经参加过该团", "收货成功", "拼团活动已经结束"
            ],
            back_click: ["请不要频繁点击提醒", "已提醒卖家发货"],
            changeValue: "已超过最大金额",
            copyOk: "复制成功",
            setAdds: "请先设置收货地址",
            errorTip: "未知错误",
            moneyMin: "金额不足以支付商品价格",
        },
        myOrder: {
            showFhDiv: "请选择发货商品",
            closeOk: "关闭成功",
            send: ["请填写完整信息", "发货成功"],
            confirm: ["操作成功", "拒绝成功", "退款成功"]
        },
        orderDetailsr: {
            laikePayThree: ["请选择支付方式", "请选择门店", "创建订单失败,请稍后再试"],
            maxTip: "已超过最大金额",
            moneyMin: "金额不足以支付商品价格",
            chooseStore: "请选择门店",
            seckillFail: "手速慢了哦，已经就被抢完了",
            shdz: "请完善收货地址",
            notCoupon: "不能使用该优惠券"
        }
    },
    productSelect: {
        classify: "分类",
        beforeClass: "请先选择分类",
        subclass: "子类",
        brand: "品牌",
        more: "更多",
        productName: "商品名称",
        productNamePlaceholder: "输入商品的名称",
        cancel: "取消",
        confirm: "确定",
        productNameTips: "请填写商品名称",
    },
    chooseAddress: {
        receivingWay: "收货方式",
        claim: "自提",
        courier: "快递",
        selectStore: "请选择门店",
        addAddress: "点击添加地址"
    },
    choosePay: {
        choosePay: "请选择支付方式",
        yuePay: "余额支付",
        yue: "余额",
        baiduPay: "百度支付",
        weChatPay: "微信支付",
        alipay: "支付宝支付"
    },
    paymodel: {
        iptPassword: "输入支付密码",
        forgot: "忘记密码",
        del: "删除",
        iSee: "我知道了"
    },
    submitOrder: {
        total: "付款金额：",
        rate: "共优惠：",
        submit: "立即支付"
    },
    ruleModal: {
        btn: "我知道了"
    },
    tabBar: [
        "首页",
        "全部分类",
        // #ifdef MP-WEIXIN

        // #endif
        "购物车",
        "我的"
    ],
    login: {
        topRight: "注册",
        or: "或",
        page1: {
            title: "密码登录",
            zhanghao_placeHolder: "请输入账号/手机号",
            mima_placeHolder: "请输入密码",
            forgot: "忘记密码",
            topBtn: "登录",
            bottomBtn: "验证码登录"
        },
        page2: {
            title: "验证码登录",
            tel_placeHolder: "请输入手机号",
            code_placeHolder: "请输入验证码",
            getCode: "获取验证码",
            countdown: "后可重获",
            topBtn: "登录",
            bottomBtn: "密码登录"
        },
        bottomIcon: "注册/登录即代表已同意",
        nopassword: "账号或密码不能为空",
        loginSuc: "登录成功！",
        yzmTips: "请先获取验证码！",
        yzmEmpty: "验证码不能为空！",
        telTips: "手机号码输入错误！",
        yzmTips1: "请输入完整的验证码！",
    },
    register: {
        topRight: "登录",
        title: "注册",
        zhanghao_placeHolder: "请输入账号（6-15位字母或数字）",
        mima1_placeHolder: "请输入6-16位数的新密码",
        mima2_placeHolder: "请再次输入密码",
        tel_placeHolder: "请输入手机号",
        code_placeHolder: "请输入验证码",
        btn: "注册",
        bottomIcon: "注册即代表已同意",
        zhanghaoTips: "请输入6-15位数字或字母账号！",
        mimaTips1: "请输入6-15位数字或字母密码！",
        mimaTips2: "确认密码与密码不一致",
        registerOk: "注册成功！",
        telTips: "请输入正确的手机号码！",
        yzmTips: "验证码输入错误！",
        mimaTips3: "两次密码输入不一致，请重新输入！",
        wanzhengTips: "请填写完整信息！"
    },
    retrievepassword: {
        title: "找回密码",
        title1: "重置密码",
        zhanghao_placeHolder: "请输入账号",
        nextBtn: "下一步",
        code_placeHolder: "验证码",
        getCode: "获取验证码",
        countdown: "后可重获",
        mima1_placeHolder: "请输入6-15位数字或字母密码!",
        mima2_placeHolder: "确认新密码",
        saveBtn: "保存",
        captchaEmpty: "验证码不能为空！",
        captchaFail: "验证码输入错误！",
        zhanghaoTips: "请输入6-15位数字或字母账号！",
        mimaTips1: "两次密码输入不一致，请重新输入！",
        mimaTips2: "密码格式错误！",
        noGetCaptcha: "获取验证码失败，请稍后再试。"
    },
    my: {
        loginPrompt: "Hi~等你很久了",
        signIn: "签到",
        toLogin: "登录/注册",
        couponNum: "优惠券",
        integralNum: "积分",
        remainingNum: "余额",
        messageNum: "消息",
        openVip_left: "开通即享会员",
        openVip_right: "大权益",
        myOrder: "我的订单",
        seeOrder: "查看全部",
        dfk_order: "待付款",
        dfh_order: "待发货",
        dsh_order: "待收货",
        dpj_order: "待评价",
        th_order: "退款/售后",
        my_store: "我的店铺",
        my_group: "我的拼团",
        my_seckill: "我的秒杀",
        my_bargain: "我的砍价",
        my_bidding: "我的竞拍",
        my_exchange: "我的兑换",
        my_distribution: "代理中心",
        my_collection: "我的收藏",
        address: "收货地址",
        service: "在线客服",
        aboutUs: "关于我们",
        languages: "切换语言",
        endTime: "到期",
        authorization: "授权",
        langList: ["中文", "英文"],
        Tips:['您的会员即将到期','马上续费','全场','折','专属活动','快速发货','立即续费','勾选不再显示']
    },
    setUp: {
        title: "设置",
        bindPhone: "绑定手机号",
        changePhone: "修改手机号",
        bindPswd: "设置登录密码",
        changePswd: "修改登录密码",
        bindPaypswd: "设置支付密码",
        changePaypswd: "修改支付密码",
        bottomBtn: "退出登录",
        noBind: "您未绑定手机号码，请先绑定手机号"
    },
    mycoupon: {
        title: "优惠券",
        tabBar: ["未使用", "已使用", "已过期"],
        activity_type: ["免邮券", "满减券", "折扣券", "会员赠券", "兑换券"],
        endTime: "到期",
        coupon_mail: "包邮",
        coupon_discount: "折",
        instructions: "使用说明",
        toUse: "立即使用",
        beUse: "已使用",
        expired: "已过期",
        instructionsText: ["1、本券可用于兑换指定商品，不能与其它优惠一同使用。", "2、本券一次只能使用一张，自领取日起", "日内有效。"],
        noCoupon: "暂无对应优惠券~",
        bottomBtn: "去领更多券"
    },
    shoppingCart: {
        title: "购物车",
        unLoginText: "登录后同步购物车中的商品",
        unLoginBtn: "登录",
        noShop: "购物车是空的",
        noShopBtn: "去逛逛",
        recommend: "为你推荐",
        topRight1: "编辑",
        topRight2: "完成",
        checkAll: "全选",
        combined: "合计：",
        settlement: "结算",
        delBtn: "删除商品",
        delDisc: "确认删除选中的商品吗？",
        cancel: "取消",
        confirm: "确认",
        takeDown: "已下架",
        soldOut: "已售罄",
        vipPrice: "会员价",
        proDown: "商品已下架",
        soldOut1: "商品已售罄",
        addSuc: "添加成功，在购物车等您哦~",
        kucunTips: "库存不足",
        chooseAttrTips: "请选择完整的商品规格！",
        reduceNo: "该宝贝不能减少了哟！",
        addNo: "数量已达到上线哦！",
        chooseDelPro: "请选择您需要删除的商品！",
        payFail: "支付发生异常!",
        choosePayPro: "请选择您需要购买的商品！",
        prokucunTips: "该商品库存不足",
        prokucunTips1: "商品库存不足，不能进行该项操作！"
    },
    myScore: {
        title: "我的积分",
        instructions: "使用说明",
        availableIntegral: "当前可用积分",
        signIn: "签到领积分",
        allDetail: "全部明细",
        gainDetail: "获取明细",
        useDetail: "使用明细",
        rulesTitle: "使用规则"
    },
    myWallet: {
        title: "我的钱包",
        money: "账户余额",
        recharge: "充值",
        withdrawal: "提现",
        walletDetails: "钱包明细",
        haswithdrawal: "已有一笔提现申请中"
    },
    recharge: {
        title: "充值",
        prompt: "充值以后可以使用余额进行交易支付",
        money: "充值金额(元)",
        money_placeholder: "金额不小于",
        paymentStyle: "请选择支付方式",
        alipay: "支付宝",
        weChat: "微信支付",
        baiduPay: "百度",
        btn: "立即充值",
        toasts: ["充值金额不小于", "元,请重新输入!", "请输入充值金额！", "请选择支付方式！", "支付成功", "充值成功！"],
        hint: "提示",
        modalTips: ["充值失败,请稍后再试", "支付失败，返回我的钱包！"]
    },
    putForward: {
        title: "提现申请",
        withdrawal: "提现金额",
        money_placeholder: "可提现金额(元)为",
        allBtn: "全部提现",
        minWithdrawal: "最小提现金额",
        poundage: "提现手续费",
        information: "填写提现银行卡信息",
        number: "银行卡号",
        number_placeholder: "请输入银行卡号",
        bank: "开户银行",
        bank_placeholder: "请输入银行名称",
        cardholder: "持卡人",
        cardholder_placeholder: "请输入持卡人姓名",
        phone: "手机号",
        phone_placeholder: "请输入手机号",
        verification: "验证码",
        verification_placeholder: "请输入手机验证码",
        getCode: "获取验证码",
        countdown: "后可重获",
        bottomBtn: "确认提现",
        noWithdraw: "您暂时没有可提现金额",
        moneyTips: ["提现金额需大于", "元,请重新输入!", "提现金额不能大于总金额，请重新输入!"],
        bankTip: "银行卡号输入错误，请重新输入！",
        bankpTips: ["请输入合法的银行卡号！", "银行卡号输入错误，请重新输入！"],
        nameTip: "请输入合法的姓名！",
        telTip: "请输入正确的手机号码！",
        tixianTip: "提现申请成功！",
        yzmTip: "请先获取验证码！",
        telTip1: "手机号码输入不一致,请确认后提交！",
        wzTip: "请填写完整信息！",
        branch: '开户支行',
        branch_placeholder: '请输入开户支行'
    },

    // 售后列表
    afterSale: {
        title: "退款/售后",
        search_placeholder: "请输入商品名称/订单号",
        search_btn: "搜索",
        return_types: ["退货退款", "仅退款", "退换·退换成功", "退换"],
        return_end: "-退款成功",
        details: "查看详情",
        service: "联系客服",
        receipt: "确认收货",
        return_text: ["退换中", "寄回商品", "查看物流"],
        noOrder: "您还没有相关的订单哦",
        goHome: "去逛逛",
        information: "填写物流信息",
        return_address: "退货地址",
        return_contact: "退货联系人",
        return_phone: "退货联系人电话",
        courierName: "快递名称",
        select_express: "请选择快递名称",
        courierNumner: "快递单号",
        courierNumner_placeholder: "填写快递单号",
        contact: "联系人",
        contact_placeholder: "请填写联系人姓名",
        phone: "联系电话",
        phone_placeholder: "请填写电话号码",
        submit: "提交",
        cancel: "取消",
        confirm: "确认",
        searchTips: "请输入搜索关键词",
        goodsSuc: "收货成功",
        submitOk: "提交成功",
        complete_info: '请填写完整信息！',
        cancelAudit: "撤销审核",
    },

    // 售后详情
    afterDetail: {
        title: "售后详情",
        type_list: ["待审核", "退换中", "退款失败", "退换失败", "退款成功", "退换成功"],
        typeDisc_list: [
            "您的售后申请正在审核中，请耐心等待2-3个工作日",
            "请您寄回商品，并填写商品寄回物流信息",
            "您的回寄商品需要3-5个工作日完成审核，请耐心等待",
            "您的售后申请已通过，退款金额于2-3个工作日到账",
            "商品已发货",
            "买家确认收货，售后完成！",
            "买家确认收货，退换成功！",
            "拒绝原因："
        ],
        record: "协商记录",
        merchants_logistics: "商家退换物流信息",
        courier_name: "快递名称",
        courier_number: "快递单号",
        return_date: "退换日期",
        buyer_logistics: "买家回寄物流信息",
        contact: "联系人",
        contact_phone: "联系电话",
        return_date1: "回寄日期",
        after_address: "售后地址",
        return_address: "退货地址",
        contact_phone1: "联系人电话",
        after_information: "售后信息",
        product_name: "商品名称",
        order_no: "订 单 号",
        apply_time: "申请时间",
        after_type: "售后类型",
        after_typeList: ["退货退款", "退换", "仅退款"],
        apply_reason: "申请原因",
        upload_documents: "上传凭证",
        amount: "退款金额",
        receiving: '已收货'
    },
    // 砍价列表
    bargain: {
        title: "热门砍价",
        days: "天",
        startAfter: "后开始",
        endAfter: "后结束",
        bargainBtn: "立即砍价",
        Bargaining_success:'砍价成功',
        Bargaining_failed: '砍价失败',
        continueBtn: "继续砍价",
        details: "查看详情",
        notBegun: "未开始",
        hasEnded: "已结束",
        myBargain: "我的砍价",
        moneyArr: [
            "已砍",
            "元，还差",
            "元"
        ],
        payment: "砍价成功，待付款",
        lowest: "已砍至最低价，砍价成功",
        nolowest: "未砍至最低价，砍价失败",
        timeout: "砍价失败，付款超时",
        payment1: "砍价成功，去付款",
        account_paid: "砍价成功,已付款！",
        cancelOrder: "取消订单",
        finish: "后结束",
        toPay: "去付款",
        obligation: "待付款",
        no_bargainText: "您暂时还没有砍价的商品哦~",
        no_bargainBtn: "去逛逛",
        prompt: "提示",
        promptContent: [
            "砍价失败，是否查看详情？",
            "此商品砍价结束，是否查看详情？",
            "您已参与此商品的砍价活动，是否查看详情？",
            "您已完成砍价，是否查看详情？",
            "您已付款此商品，是否查看详情？"
        ],
        cancel: "否",
        confirm: "是"
    },
    // 砍价页面
    bargainIng: {
        title: "超值砍价",
        rules: "砍价规则",
        helpMe: "我正在砍一件好货，来帮我砍价吧！",
        days: "天",
        finish: "后结束",
        timeout: "对不起您的砍价时间已到，砍价失败",
        afterBargaining: "砍价后",
        yuan: "元",
        moneyArr: [
            "已砍",
            "元，还差",
            "元"
        ],
        friendSuccess: "您已帮好友砍价成功",
        success: "恭喜您已完成砍价",
        friendShare: "帮好友分享此砍价",
        share: "分享给好友，多砍一刀",
        toPay: "去付款",
        obligation: "待付款",
        orderDetails: "查看订单详情",
        finished: "已结束",
        helpFriend: "帮好友砍一刀",
        seeMore: "去看更多砍价",
        meToo: "我也去砍价",
        bargainFor: "砍价帮",
        cutDown: "砍掉",
        packUp: "收起",
        unfold: "展开",
        beCutDown: "您已砍",
        cutFriend: "您已帮好友砍",
        shareFriend: "分享给好友帮你砍价！",
        iSee: "知道啦",
        saveImg: "保存图片",
        weChatFriends: "微信好友",
        shareWay: [
            // #ifndef MP-WEIXIN
            '微信',
            '朋友圈',
            // #endif
            '二维码分享',
        ],
        iKown: "我知道了",
        noLogin: "未登录，请先登录",
        saveImgOk: "保存图片成功",
        copyOk: "复制分享链接成功！",
        copyFail: "复制分享链接失败！",
        shareOk: "分享成功!",
        shareFail: "分享失败!",
    },
    // 砍价确认订单
    bargainDetailsr: {
        title: "确认订单信息",
        vipDiscount: "会员等级折扣",
        fold: "折",
        distributionDiscount: "分销等级购物折扣",
        freight: "运费",
        freeShipping: "免邮",
        orderRemarks: "订单备注",
        orderRemarks_placeholder: "选填，请先和商家协商一致",
        Total: "合计：",
    },
    // 竞拍列表
    bidding: {
        title: "竞拍",
        header: ["正在热拍", "即将开拍"],
        startingPrice: "起拍价",
        participation: "参与",
        people: "人",
        bidBy: "出价幅度",
        time: "/次",
        notBegun: "未开始",
        begin: "开始",
        waitAuction: "待开拍",
        finish: "结束",
        auction: "竞拍",
        finished: "已结束",
        noPro: "暂时还没有新的竞拍商品哦~",
        prompt: "提示",
        show_content: [
            "尊敬的会员,你已在该活动中上交了押金",
            "尊敬的会员，你已经竞拍到了该商品请前去付款",
            "尊敬的会员，你已生成待付款订单请前去支付"
        ],
        cancel: "取消",
        confirm: "确定"
    },
    // 竞拍详情
    bidding_detailed: {
        title: "竞拍",
        rules: "竞拍规则",
        finished: "已结束",
        fromEnd: "距结束",
        fromStart: "距开始",
        days: "天",
        share: "分享",
        startingPrice: "起拍价",
        LatestPrice: "最新价",
        marketPrice: "市场价",
        freight: "运费",
        freeFreight: "包邮",
        participation: "参与",
        people: "人",
        myDynamics: "我的竞拍动态",
        offerPrice: "已出价",
        yuan: "元",
        bidFailed: "未成功出价",
        dynamic: "竞拍动态",
        offer: "出价",
        congratulations: "恭喜用户",
        use: "以",
        getGoods: "的价格拍得本商品",
        record: "竞拍记录",
        strip: "条",
        auctionType: "拍卖类型",
        commonBidding: "普通竞拍",
        securityFund: "保证金",
        bidIncrement: "加价幅度",
        startTime: "开拍时间",
        endTime: "结束时间",
        process: "参拍流程",
        intoShop: "进店逛逛",
        sellingGoods: "在售商品",
        soldOut: "已售",
        followers: "关注人数",
        described: "拍品描述",
        specification: "规格:",
        time: "/次",
        noAction: "未开拍",
        enterBid: "进入出价",
        nopro: "暂时还没有相关的竞拍产品哦",
        canBuy: "可以去看看有那些想买的",
        goHome: "去商城逛逛",
        load: "加载中",
        rentDeposit: "支付保证金",
        auctionBid: "竞拍出价",
        paymentStyle: "请选择支付方式",
        alipay: "支付宝",
        weChat: "微信支付",
        baiduPay: "百度支付",
        yue: "余额支付",
        lowestBid: "当前最低出价为",
        cancel: "取消",
        confirm: "确定",
        inputPwsd: "请输入支付密码",
        toSetupPwsd: "无支付密码，前往设置！",
        toSetup: "去设置",
        saveImg: "保存图片",
        weChatFriends: "微信好友",
        weChatMoments: "微信朋友圈",
        qrCode: "二维码分享",
        ongoing: "正在进行中",
        obligation: "待付款",
        done: "已完成",
        lostAuction: "本次活动已流拍，感谢您的参与",
        afterContinue: "s后继续竞拍",
        prompt: "提示",
        auctionEnd: "本次竞拍结束！",
        toPayText: "尊敬的会员，你已经竞拍到了该商品请前去付款",
        noLessThan: "出价不得低于",
        saveImgOk: "保存图片成功",
        saveImgFail: "保存图片失败",
        copyOk: "复制成功",
        moneySmill: "出价幅度过低",
        amountTips: "请输入正确的金额",
        premiumOk: "加价成功",
        premiumFail: "出价失败,",
        paidSuccess: "上交押金成功",
        mimaFail: "您输入密码错误,请重新输入",
        mimaTips: "请输入完整密码！",
        nobalance: "余额不足，请充值",
        toChujia: "即将为您跳转出价页面",
        lingxian: "领先",
        chuju: "出局"
    },
    // 竞拍规则
    bidding_rule: {
        title: "竞拍规则",
        load: "加载中",
    },
    // 我的竞拍
    bidding_my: {
        title: "我的竞拍",
        startingPrice: "起拍价",
        offer: "出价",
        people: "人",
        bidBy: "出价幅度",
        time: "/次",
        ongoing: "进行中",
        finished: "已结束",
        obligation: "待付款",
        done: "已完成",
        agoOrder: "前下单",
        cutOff: "截止",
        continueAuction: "继续竞拍",
        myOrder: "我的订单",
        noOrderText: "您暂时还没有相关的订单哦",
        noOrderText1: "可以去看看有那些想买的",
        goHome: "去逛逛"
    },
    // 竞拍确认订单信息
    bidding_order: {
        title: "确认订单信息",
        vipDiscount: "会员等级折扣",
        fold: "折",
        distributionDiscount: "分销等级购物折扣",
        freight: "运费",
        freeShipping: "免邮",
        orderRemarks: "订单备注",
        orderRemarks_placeholder: "选填，请先和商家协商一致",
        subtotal: '小计',
        discount: '会员折扣减',
        member_price: '会员价'
    },
    // 出价记录
    bidding_record: {
        title: "出价记录",
        user: "用户",
        state: "状态",
        time: "时间",
        bidPrice: "竞拍价",
        leading: "领先",
        out: "出局",
        noRecord: "暂时还没有相关的竞拍记录哦",
        load: "加载中"
    },
    // 代理中心
    distribution_center: {
        title: "代理中心",
        referrer: "推荐人：",
        myPromotion: "我的推广",
        expect: "预计佣金",
        canWithdraw: "可提现佣金",
        total: "累计佣金",
        agentShop: "代理商城",
        withdrawal: "佣金提现",
        myTeam: "我的团队",
        commissionSubsidiary: "佣金明细",
        withdrawalSubsidiary: "提现明细",
        rules: "分销规则",
        noDistribution: "您暂无权限请升级成为代理",
        upDistribution: "立即升级成为代理",
        load: "加载中",
        reviewRecordTips: "您还有一笔正在审核中的提现记录！",
    },
    // 佣金明细
    distribution_flow: {
        title: "佣金明细",
        total: "总佣金",
        yuan: "元",
        status: "发放状态：",
        noFlow: '您还没有相关记录~'
    },
    // 佣金提现
    distribution_form: {
        title: "佣金提现",
        withdrawalAmount: "提现金额",
        withdrawal_placeholder: "可提现金额为",
        yuan: "元",
        allWithdrawal: "全部提现",
        minimum: "最小提现金额",
        maximum: "， 最大提现金额",
        withdrawalFee: "， 提现手续费",
        cardInformation: "填写提现银行卡信息",
        name: "持卡人",
        namePlaceholder: "请输入持卡人姓名",
        bankNumber: "银行卡号",
        bankNumberPlaceholder: "请输入银行卡号",
        bank: "开户行",
        bankPlaceholer: "请输入开户行",
        branch: "开户支行",
        branchPlaceholder: "请输入开户支行",
        tel: "手机号",
        telPlaceholder: "请输入手机号",
        telcode: "验证码",
        telcodePlaceholder: "请输入手机验证码",
        getcode: "获取验证码",
        countdown: "后再次获取",
        complete: "完成",
        withdrawalTips: "提现金额不能小于最低限额",
        nameTips: "请输入合法的姓名！"
    },
    // 代理商城
    distribution_list: {
        title: "代理商城",
        vip_yprice: "会员价",
        nopro: "该等级暂时没有商品！"
    },
    // 提现结果
    distribution_result: {
        title: "提现",
        failText: "提现申请失败",
        failReason: "审核失败原因",
        successText: "提现申请成功",
        successText1: "提现金额将在3个工作日内到账，请注意查收",
        cashCard: "提现银行卡",
        tail: "尾号",
        amount: "提现金额",
        complete: "完成",
        auditText: "提现申请审核中",
        auditing: "正在审核中，请耐心等待。",
    },
    // 代理规则
    distribution_rule: {
        title: "代理规则"
    },
    // 扫码分享
    distribution_share: {
        title: "扫码分享",
        save: "保存"
    },
    // 我的团队
    distribution_team: {
        title: "我的团队",
        level: "分销等级：",
        lower: "下级代理",
        noteam: "暂时还没有下级哦",
        load: "加载中"
    },
    // 提现明细
    distribution_tocashFlow: {
        title: "提现明细",
        accumulative: "累计提现佣金",
        yuan: "元",
        header: ['全部', '待审核', '审核通过', '审核失败'],
        withdrawal: "提现",
        noFlow: "您还没有任何记录~",
        statusStr: ['审核中', '审核成功', '审核失败'], 
    },
    // 拼团列表
    group: {
        title: "拼团",
        todayGroup: "今日拼团",
        trailer: "拼团抢先知",
        noGroup: "暂时还没有拼团活动哦",
        goHome: "去逛逛",
        gone: "已抢光",
        finished: "已结束",
        haveGroup: "已团",
        unit: "件",
        peopleGroup: "人团",
        single: "单买价",
        goGroup: "去拼团",
        days: "天",
        begin: "后开抢",
    },
    // 一起拼团
    group_end: {
        title: "一起拼团",
        peopleGroup: "人团，",
        haveGroup: "已团",
        unit: "件",
        less: "还差",
        peopleSuccse: "人拼团成功，",
        endAfter: "后结束",
        groupSuccess: "拼团成功",
        groupFail: "拼团失败,款项将在2个工作日内原路退回",
        captain: "团长",
        inviteFriends: "立即邀请好友参团",
        productName: "商品名称：",
        amount: "支付金额：",
        groupAgain: "拼团结束，再次开团",
        groupAgain1: "继续拼团",
        checkOrder: "查看订单",
        tuxedo: "立即参团",
        joinAnother: "或参加别人的团",
        peopleGroups: "人成团",
        remaining: "剩余",
        goTuxedo: "去参团",
        groupPlay: "拼团玩法",
        rules: "拼团规则",
        clickOpen: "点击开团",
        orTuxedo: "或参团",
        invitation: "邀请",
        friendInGroup: "好友参团",
        achieve: "达到",
        spellGroup: "拼团人数",
        group_success: "组团成功",
        waitDelivery: "等待发货",
        inventory: "库存",
        quantity: "购买数量",
        confirm: "确认",
        saveImg: "保存图片",
        weChat: "微信",
        weChatFriends: "微信好友",
        weChatMoments: "朋友圈",
        qrCode: "二维码",
        load: "加载中",
        iSee: "我知道了",
        saveImgOk: "保存图片成功",
        saveImgFail: "保存图片失败",
        copyOk: "复制分享链接成功",
        copyFail: "复制分享链接失败",
        noReduce: "数量已经减少到最低了哦",
        noStock: "库存不足",
        selectAllTips: "请选择完整商品规格",
        selectAllTips1: "请选择完整拼团人数",
        nostart: "活动暂未开始，无法购买",
        activityOver: "活动已结束，无法购买",
        noAgain: "此商品无法再次参团",
        upperLimit: "已达参团上限，无法继续参团",
    },
    // 拼团商品详情
    groupDetailed: {
        title: "商品详情",
        peopleGroup: "人拼团",
        single: "单买价",
        activityOver: "活动已结束",
        days: "天",
        fromStart: "距开始",
        fromEnd: "距结束",
        afterEnd: "距结束已有",
        freight: "运费：",
        selectSize: "选择商品规格",
        followingPartners: "以下小伙伴正在发起拼团",
        alreadyHave: "已有",
        less: "还差",
        peopleGroups: "人成团",
        remaining: "剩余",
        goTuxedo: "去参团",
        groupPlay: "拼团玩法",
        rules: "拼团规则",
        clickOpen: "点击开团",
        orTuxedo: "或参团",
        invitation: "邀请",
        friendInGroup: "好友参团",
        achieve: "达到",
        spellGroup: "拼团人数",
        group_success: "组团成功",
        waitDelivery: "等待发货",
        comments: "用户评价",
        anonymous: "匿名",
        noEvaluation: "暂无评价",
        intoShop: "进店逛逛",
        sellingGoods: "在售商品",
        soldOut: "已售",
        followers: "关注人数",
        goodsDetails: "商品详情",
        productName: "商品名称：",
        brand: "品牌：",
        productID: "商品编号：",
        classify: "分类：",
        afterSale: "售后：",
        conditions: "签收之日起48小时内无条件退货",
        kefu: "客服",
        fx: "分享",
        purchase: "单独购买",
        wantOpen: "我要开团",
        notBut: "活动还未开始，暂时不能购买~",
        notGroup: "活动还未开始，暂时不能开团~",
        inventory: "库存",
        quantity: "购买数量",
        groupType: "拼团类型",
        confirm: "确认",
        saveImg: "保存图片",
        inviteLink: "邀请链接",
        cancel: "取消",
        copy: "复制链接",
        shareTo: "分享至",
        weChatFriends: "微信好友",
        weChatMoments: "微信朋友圈",
        qrCode: "二维码分享",
        iSee: "我知道了",
        eventOver: "活动已经结束!",
        copyOk: "复制分享链接成功！",
        copyFail: "复制分享链接失败！",
        selectAttrTips: "请选择完整商品规格！",
        selectNumberTips: "请选择完整拼团人数！",
        stockNo: "库存不足！",
        activityOver: "活动已结束，无法购买！",
    },
    // 我的拼团
    groupOrder: {
        title: "我的拼团",
        header: ["全部", "待付款", "拼团中", "拼团成功", "拼团失败"],
        obligation: "待付款",
        sale_button:['待发货-已退款','待收货-已退款','已收货-已退款'],
        dfh_order: "拼团成功-待发货",
        yfh_order: "拼团成功-已发货",
        dpj_order: "拼团成功-待评价",
        pt_success:'拼团成功-已关闭',
        spelling: "拼团中",
        refunding: "拼团失败-退款中",
        noRefund: "拼团失败-未退款",
        refunded: "拼团失败-已退款",
        Failed:'拼团失败-已关闭',
        closed: "交易关闭",
        complete: "交易完成",
        returnOf: "退货中",
        returnComplete: "退货完成",
        together: "共",
        items: "件商品",
        Total: "合计：",
        leftText: ["取消订单", "查看物流", "删除订单", "查看详情", "拼团详情"],
        rightText: ["立即付款", "提醒发货", "确认收货", "立即评价", "退货", "追加评价", "再次购买", "拼团详情", "邀请好友"],
        noOrder: "您还没有相关的订单哦",
        goHome: "去逛逛",
        cancelOk: "取消成功！",
        hasDelivered: "卖家已发货！",
        networkBusy: "网络繁忙请稍后再试！",
        loadFail: "数据加载失败！",
        delOk: "删除成功！",
        noStockTips: "部分商品库存不足，无法再次购买",
        hasRemind: "已提醒卖家发货！",
        receivedOk: "收货成功！",
        receivedFail: "确认收货失败！"
    },
    // 拼团确认订单
    groupPayfor: {
        title: "确认订单信息",
        yuan: "元",
        peopleGroup: "人团",
        vipDiscount: "会员等级折扣",
        fold: "折",
        distributionDiscount: "分销等级购物折扣",
        freight: "运费",
        freeShipping: "免邮",
        orderRemarks: "订单备注",
        orderRemarks_placeholder: "选填，请先和商家协商一致",
        Total: "合计：",
        payOk: "支付成功",
        setAddsTips: "请先设置收货地址",
        goupTips1: "最多只能同时拼",
        goupTips2: "个团",
        vipPrice: "会员价：",
        vipDiscount1: "会员折扣减："
    },
    // 添加平台活动商品
    activities_add: {
        title: "添加活动商品",
        size: "规格：",
        kucun: "库存：",
        checkAll: "全选",
        selected: "已选",
        items: "款商品",
        btn_name: "活动设置",
        btn_name_ms: "秒杀设置",
        btn_name_pt: "拼团设置",
        pleaseChoose: "请选择商品",
        classify: "分类",
        brand: "品牌"
    },
    // 平台活动详情
    activities_details: {
        title: '活动详情',
        title_pt: '拼团活动详情',
        title_ms: '秒杀活动详情',
        notBegun: "未开始",
        ongoing: "进行中",
        finished: "已结束",
        activityType: "活动类型：",
        proPt: "拼团",
        proMs: "秒杀",
        activityTime: "活动时间：",
        to: "至",
        activityRules: "活动规则：",
        ptRules: [
            "人团，拼团时间为",
            "小时，用户最多可开团",
            "个，参团",
            "次，",
            "可重复参团",
            "不可重复参团"
        ],
        msRules: [
            "包邮",
            "不包邮",
            "，秒杀时段分别为",
            "，限购",
            "个"
        ],
        registrationTime: "报名时间：",
        setGoods: "设置活动商品",
        timeNoStart: "活动报名时间还未开始",
        timeClose: "活动报名时间已截止！",
    },
    // 平台活动商品列表
    activities_pro: {
        title: "活动商品",
        goodList: "商品列表",
        examined: "待审核商品",
        size: "规格：",
        kucun: "库存：",
        pendingReview: "待提交审核",
        inReview: "审核中",
        auditFailure: "审核失败：",
        undo: "撤销",
        delete: "删除",
        addInventory: "追加库存",
        editor: "编辑",
        submit: "提交",
        addGoods: "添加活动商品",
        nogoods: "您还没有审核通过的活动商品哦~",
        nogoods1: "您还没有审核中的活动商品哦~",
        addInventoryPlaceholder: "请输入追加的库存数量",
        totalInventory: "当前商品总库存量：",
        cancel: "取消",
        confirm: "确认",
        inventoryTips: "请填写追加库存数量",
        addinventoryTips: "追加的库存数量不能大于商品总库存量",
    },
    // 平台活动设置
    activities_set: {
        title: "活动设置",
        title_pt: "拼团设置",
        title_ms: "秒杀设置",
        title_edit: "编辑商品",
        size: "规格：",
        kucun: "库存：",
        activeKucun: "活动库存：",
        activeKucunPlaceholder: "请输入活动库存",
        submit: "提交",
        submit1: "立即报名",
        totalInventory: "当前商品总库存量：",
        success: "成功"
    },
    // 库存管理
    addStock: {
        title: "库存管理",
        load: "加载中",
        inventory: "剩余库存",
        warning: "库存预警",
        addInventory: "添加库存",
        save: "保存",
        tips: ["已超过最大可减少的库存数量", "修改成功"]
    },
    // 门店信息设置
    addStore: {
        title: "门店信息设置",
        storeName: "门店名称",
        storeNamePlaceholder: "请输入门店名称",
        tel: "联系电话",
        telPlaceholder: "请输入联系电话",
        times: "营业时间",
        timesPlaceholder: "请输入营业时间",
        city: "所在城市",
        cityPlaceholder: "请选择省/市/区",
        address: "详细地址",
        addressPlaceholder: "请输入详细地址",
        save: "保存",
        del: "删除",
    },
    // 用户协议
    userAgreement: {
        title: '用户协议'
    },
    // 店铺入驻协议
    applyAgreement: {
        title: "入驻协议",
        load: "加载中"
    },
    // 申请开店
    applyStore: {
        title: "申请开店",
        shopName: "店铺名称",
        shopNamePlaceholder: "请填写店铺名称",
        nameExisting: "该店铺名已经存在，请重新填写",
        information: "店铺信息",
        informationPlaceholder: "请填写店铺简介信息（50字以内）",
        business: "经营范围",
        businessPlaceholder: "请填写店铺经营范围",
        username: "用户姓名",
        usernamePlaceholder: "请填写真实姓名",
        IDnumber: "身份证号",
        IDnumberPlaceholder: "请填写身份证号",
        tel: "联系电话",
        telPlaceholder: "请填写联系电话",
        address: "联系地址",
        addressPlaceholder: "请填写联系地址",
        nature: "所属性质",
        personal: "个人",
        enterprise: "企业",
        license: "营业执照",
        upload: "上传营业执照",
        read: "我已阅读并了解",
        agreement: "申请入驻协议",
        submit: "提交申请",
        agreementFail: "请勾选我已阅读协议",
        shopNameFail: "店铺名称不能为空",
        informationFail: "店铺信息不能为空",
        usernameFail: "用户姓名不能为空",
        IDFail: "身份证号不能为空",
        telFail: "联系电话不能为空",
        addressFail: "联系地址不能为空",
        businessFail: "经营范围不能为空",
        IDFail1: "请输入正确的身份证号",
        telFail1: "请输入正确的联系电话"
    },
    // 店铺申请结果
    applySuc: {
        title: "申请结果",
        submittedSuccse: "入驻申请提交成功",
        waitReview: "请耐心等待工作人员审核"
    },
    // 自选商品
    choose_shopping: {
        title: "自选商品",
        classify: "分类",
        beforeClass: "请先选择分类",
        subclass: "子类",
        brand: "品牌",
        more: "更多",
        productName: "商品名称",
        productNamePlaceholder: "输入商品的名称",
        cancel: "取消",
        confirm: "确认",
        productNameTips: "请填写商品名称",
        kucun: "库存：",
        nopro: "暂时还没有未选择商品",
        checkAll: "全选",
        selected: "已选",
        items: "款商品",
        add: "添加",
        pleaseChoose: "请选择商品",
        addSuc: "添加成功",
        nofreight: '请先设置运费'
    },
    // 优惠券选择指定分类
    chooseClass: {
        title: "选择分类",
        save: "确定",
        saveFail: "请选择分类"
    },
    // 优惠券选择指定商品
    choosePro: {
        title: "选择商品",
        title1: "已选商品",
        searchName: "请输入商品名称",
        searchBtn: "搜索",
        inventory: "库存：",
        checkAll: "全选",
        selected: "已选",
        items: "款商品",
        confirm: "确定",
        complete: "完成",
        editor: "编辑",
        del: "删除",
        continueAdd: "继续添加",
        chooseProTips: "请选择商品"
    },
    // 店铺优惠券
    storeCoupon: {
        title: "优惠券",
        edit: "编辑",
        issue: "发行",
        coupons: "优惠券",
        issuedCoupon: "已发行优惠券",
        type: "类型",
        typePlaceholder: "请选择优惠券类型",
        name: "名称",
        namePlaceholder: "请输入优惠券名称",
        issueNumber: "发行数量",
        issueNumberPlaceholder: "请输入发行的优惠券数量",
        zhang: "张",
        faceValue: "面值",
        faceValuePlaceholder: "请输入优惠券面值",
        yuan: "元",
        discountValue: "折扣值",
        discountValuePlaceholder: "请输入优惠券折扣值",
        discount: "折",
        threshold: "消费门槛",
        thresholdPlaceholder: "请输入优惠券使用门槛",
        range: "可用范围",
        all: "全部商品",
        specifyPro: "指定商品",
        specifyClass: "指定分类",
        chooseGoods: "选择商品",
        chooseGoodsPlaceholder: "请选择优惠券可使用的商品",
        chooseClass: "选择分类",
        chooseClassPlaceholder: "请选择优惠券可使用的分类",
        startTime: "开始时间",
        startTimePlaceholder: "请选择优惠券开始使用时间",
        endTime: "过期时间",
        endTimePlaceholder: "请选择优惠券过期时间",
        limit: "领取限制",
        limitPlaceholder: "请输入每人限领的数量",
        instructions: "使用说明",
        instructionsPlaceholder: "请输入优惠券的使用说明",
        submit: "提交",
        full: "满",
        use: "使用",
        noThreshold: "无门槛券",
        expired: "已过期",
        circulation: "发行数量：",
        remaining: "剩余数量：",
        del: "删除",
        editor: "编辑",
        record: "领取记录",
        confirmDel: "确认将此优惠券删除？",
        confirm: "确认",
        cancel: "取消",
        type_list: ["满减券", "折扣券"],
        couponTips: [
            "请选择优惠券类型",
            "请输入优惠券名称",
            "请输入发行数量",
            "请输入优惠券面值",
            "请输入优惠券折扣值",
            "请输入消费门槛",
            "请选择指定商品",
            "请选择指定分类",
            "请选择开始时间",
            "请选择结束时间",
            "请选择领取限制"
        ],
        noFx: '暂无已发行优惠券~'
    },
    // 拼团管理
    fight_manage: {
        title: "拼团管理",
        tabTitle: ["拼团成功", "拼团中", "拼团失败"],
        today: "(今天)",
        orderNo: "订单号：",
        obligation: "待付款",
        waitSend: "待发货",
        waitReceiving: "待收货",
        comment: "待评论",
        returnReview: "退货审核中",
        agreeReplacement: "同意换货",
        agreeReturn: "同意退货",
        refusedReturn: "拒绝退货",
        receiveMerchant: "待商家收货",
        agreeRefund: "同意退款",
        rejectReturn: "拒绝并退回商品",
        refusedRefund: "拒绝退款",
        agreeAndRefund: "同意并退款",
        sendMerchandise: "商家寄出商品",
        afterComplete: "售后完成",
        done: "已完成",
        orderClosed: "订单关闭",
        pt: "拼团",
        kj: "砍价",
        jp: "竞拍",
        fx: "分销",
        zt: "自提",
        total: "合计：",
        editOrder: "编辑订单",
        delivery: "发货",
        closeOrder: "关闭订单",
        audit: "审核",
        checkLogistics: "查看物流",
        refund: "退款",
        backSend: "回寄",
        refuse: "拒绝",
        verificationCode: "验证码核销",
        scanQRcode: "自提扫码",
        noOrder: "您还没有相关的订单哦",
        information: "填写物流信息",
        courierName: "快递公司",
        select_express: "请选择快递公司",
        courierNumner: "快递单号",
        courierNumner_placeholder: "请填写快递单号",
        submit: "提交",
        refusalReasons: "请填写拒绝理由",
        refusalPlaceholder: "请输入拒绝理由",
        cancel: "取消",
        confirm: "确认",
        refundSum: "请填写退款金额",
        refundSum1: "请输入退款金额",
        refundSumDisc1: "应退",
        refundSumDisc2: "，确认后款项将原路返回",
        LogFailLoadDBSystem: "数据加载失败！",
        maximumTips: "已超过最大可退还金额",
        noScan: "H5不支持扫码功能，请选择手动输入"
    },
    // 运费设置
    freight: {
        title: "运费设置",
        default1: "默认",
        see: "查看",
        edit: "编辑",
        noFreight: "您还没有运费模板哦~",
        add: "添加模板",
        beUsed: "已使用",
        unused: "未使用"
    },
    // 添加运费模板
    freight_add: {
        title: "添加模板",
        title1: "编辑模板",
        title2: "查看模板",
        name: "模板名称",
        namePlaceholder: "请输入运费模板名称",
        rules: "运费规则",
        addRule: "添加规则",
        freight: "元运费",
        setDefault: "设为默认",
        save: "保存",
        del: "删除模板",
        nameTips: "请输入运费模板名称",
        ruleTips: "请添加运费规则",
		hasSpecial: '模板名称包含特殊字符'
    },
    // 添加运费模板——添加规则模板
    freight_rules: {
        title: "添加模板",
        freight: "运费",
        freightPlacehold: "请输入运费",
        choose: "选择省份",
        choosePlacehold: "请选择省份",
        save: "保存",
    },
    // 选择省份
    freight_sheng: {
        title: "选择省份",
        checkAll: "全选",
        save: "保存",
        chooseTips: "请选择省份"
    },
    // 上传商品详情
    storeGoodsDetail: {
        title: "商品详情",
        complete: "完成",
        textPlacehold: "请输入内容",
        submit: "提交",
        cancel: "取消",
        insertText: "插文字",
        editText: "改文字",
        insertImg: "插图片",
        del: "删除",
    },
    // 修改联系地址
    storeModifyAdress: {
        title: "修改联系地址",
        area: "所在地区",
        areaplacehold: "请选择所在地区",
        address: "详细地址",
        addressPlacehold: "请填写详细地址",
        save: "保存",
        succse: "修改成功"
    },
    // 限时秒杀
    MsIndex: {
        title: "限时秒杀",
        all: "全部",
        today: "(今天)",
        orderNo: "订单号：",
        obligation: "待付款",
        waitSend: "待发货",
        waitReceiving: "待收货",
        comment: "待评论",
        returnReview: "退货审核中",
        agreeReplacement: "同意换货",
        agreeReturn: "同意退货",
        refusedReturn: "拒绝退货",
        receiveMerchant: "待商家收货",
        agreeRefund: "同意退款",
        rejectReturn: "拒绝并退回商品",
        refusedRefund: "拒绝退款",
        agreeAndRefund: "同意并退款",
        sendMerchandise: "商家寄出商品",
        afterComplete: "售后完成",
        done: "已完成",
        orderClosed: "订单关闭",
        pt: "拼团",
        kj: "砍价",
        jp: "竞拍",
        fx: "分销",
        zt: "自提",
        total: "合计：",
        editOrder: "编辑订单",
        delivery: "发货",
        closeOrder: "关闭订单",
        audit: "审核",
        checkLogistics: "查看物流",
        refund: "退款",
        backSend: "回寄",
        refuse: "拒绝",
        verificationCode: "验证码核销",
        scanQRcode: "自提扫码",
        noOrder: "您还没有相关的订单哦",
        information: "填写物流信息",
        courierName: "快递公司",
        select_express: "请选择快递公司",
        courierNumner: "快递单号",
        courierNumner_placeholder: "请填写快递单号",
        submit: "提交",
        refusalReasons: "请填写拒绝理由",
        refusalPlaceholder: "请输入拒绝理由",
        cancel: "取消",
        confirm: "确认",
        refundSum: "请填写退款金额",
        refundSum1: "请输入退款金额",
        refundSumDisc1: "应退",
        refundSumDisc2: "，确认后款项将原路返回",
        LogFailLoadDBSystem: "数据加载失败！",
        maximumTips: "已超过最大可退还金额",
        noScan: "H5不支持扫码功能，请选择手动输入",
        loading: "加载中"
    },
    // 店铺我的提现
    storeMyCha: {
        title: "我的提现",
        money: "账户金额（元）",
        tixian: "提现",
        minxi: "明细",
        instructions: "提现说明",
    },
    // 店铺我的客户
    storeMyCli: {
        title: "我的客户",
        today: "(今天)",
        yesterday: "(昨天)",
        beforeYesterday: "(前天)",
        earlier: "(更早)",
        noList: "暂时还没有客户访问哦~",
    },
    // 店铺账户明细
    myFinance: {
        title: "账户明细",
        tabList: ["收入明细", "积分明细", "提现明细"],
        tabList1: ["全部", "待审核", "审核通过", "审核失败"],
        inReview: "审核中",
        done: "已完成",
        faidDisc: "审核失败，已退回账户",
        today: "（今天）",
        balance: "余额：",
        integral: "积分：",
        noList: "暂时还没有记录哦~",
    },
    // 店铺我的订单
    storeMyOrder: {
        title: "我的订单",
        tabList: ["全部", "待付款", "待发货", "退货"],
        today: "(今天)",
        orderNo: "订单号：",
        obligation: "待付款",
        waitSend: "待发货",
        waitReceiving: "待收货",
        comment: "待评论",
        returnReview: "退货审核中",
        agreeReplacement: "同意换货",
        agreeReturn: "同意退货",
        refusedReturn: "拒绝退货",
        receiveMerchant: "待商家收货",
        agreeRefund: "同意退款",
        rejectReturn: "拒绝并退回商品",
        refusedRefund: "拒绝退款",
        agreeAndRefund: "同意并退款",
        sendMerchandise: "商家寄出商品",
        afterComplete: "售后完成",
        done: "已完成",
        orderClosed: "订单关闭",
        pt: "拼团",
        kj: "砍价",
        jp: "竞拍",
        fx: "分销",
        zt: "自提",
        total: "合计：",
        editOrder: "编辑订单",
        delivery: "发货",
        closeOrder: "关闭订单",
        audit: "审核",
        checkLogistics: "查看物流",
        refund: "退款",
        backSend: "回寄",
        refuse: "拒绝",
        verificationCode: "验证码核销",
        scanQRcode: "自提扫码",
        noOrder: "您还没有相关的订单哦",
        information: "填写物流信息",
        courierName: "快递公司",
        select_express: "请选择快递公司",
        courierNumner: "快递单号",
        courierNumner_placeholder: "请填写快递单号",
        submit: "提交",
        refusalReasons: "请填写拒绝理由",
        refusalPlaceholder: "请输入拒绝理由",
        cancel: "取消",
        confirm: "确认",
        refundSum: "请填写退款金额",
        refundSum1: "请输入退款金额",
        refundSumDisc1: "应退",
        refundSumDisc2: "，确认后款项将原路返回",
        maximumTips: "已超过最大可退还金额",
        noScan: "H5不支持扫码功能，请选择手动输入",
    },
    // 我的商品
    myPro: {
        title: "我的商品",
        tabList: ["商品列表", "待审核商品"],
        kucun: "库存：",
        volume: "销量：",
        beenOn: "已上架",
        shelves: "已下架",
        notOn: "待上架",
        delPro: "删除商品",
        stock: "库存管理",
        downPro: "下架商品",
        upPro: "上架商品",
        edit: "重新编辑",
        noGoods: "暂无商品",
        toAdd: "去添加",
        inReview: "审核中",
        approve: "审核通过",
        failAudit: "审核失败",
        noAudit: "暂不审核",
        cancelAudit: "撤销审核",
        submitAudit: "提交审核",
        addStockDisc: "请填写增加库存的数量",
        cancel: "取消",
        confirm: "确认",
        success: "操作成功",
        delSuccess: "删除成功",
    },
    // 我的店铺
    myStore: {
        title: "我的店铺",
        inReview: "审核中",
        inReviewDisc: "您的资料已提交，正在审核中，请耐心等待",
        synopsis: "简介：",
        sweepCode: "扫码核销",
        todayOrder: "今日订单数",
        noDeliveryOrder: "待发货订单",
        afterSales: "售后订单",
        visitors: "访客数",
        newIncome: "今日新增收入",
        balance: "账户金额",
        optional: "自选商品",
        shelves: "上架商品",
        myPro: "我的商品",
        myOrder: "我的订单",
        coupons: "优惠券",
        withdrawal: "我的提现",
        spellGroup: "拼团管理",
        seckill: "限时秒杀",
        activity: "活动管理",
        myCli: "我的客户",
        freight: "运费设置",
        storeSetup: "店铺设置",
        storeManag: "门店管理",
        laike: "吉采推提供技术支持",
        noStore: "您还未申请开店",
        apply: "申请开店",
        Unapprove: "审核未通过",
        reason: "原因:",
        toApply: "继续申请",
    },
    addAddress: {
        title: '添加新地址',
        title1: '编辑地址',
        consignee: '收货人',
        consignee_placeholder: '请输入收货人名称',
        contactinfo: '联系方式',
        contactinfo_placeholder: '请输入电话号码',
        region: '所在地区',
        region_placeholder: '请选择所在地区',
        addressinfo: '详细地址',
        addressinfo_placeholder: '请输入详细地址',
        defaultaddress: '默认地址',
        saveBtn: '保存',
        add_success: '添加成功！',
        complete_info: '请填写完整信息！',
        modify_success: '修改成功！',
        Receiving_verification: '收货人姓名包含特殊字符！',
    },
    receivingAddress: {
        title: '收货地址',
        edit: '编辑',
        deletes: '删除',
        addnewaddress: '添加新地址',
        defaults: '默认',
        defaultaddress: '默认地址',
        cancel: '取消',
        confirm: '确认',
        confirm_delete: '确认删除默认地址吗?',
        add_address: '添加地址',
        delete_success: '删除成功',
        complete: "完成",
        management: "管理"
    },
    collection: {
        title: '我的收藏',
        commodity_collection: '商品收藏',
        shop_collection: '店铺收藏',
        commodity_Tips: '您还没有收藏的商品哦！',
        shop_Tips: '您还没有收藏的店铺哦！',
        edit: '编辑',
        complete: '完成',
        be_similar: '看相似',
        shop: '店铺',
        people_collection: '人收藏',
        Select_all: '全选',
        Cancel_collection: '取消收藏',
        commodity_delete: '请选择需要删除的商品！',
        Cancelled_successfully: '取消成功'
    },
    discover: {
        title: '发现',
        recommend: '相似推荐',
        shop: '店铺',
        nofind: '没有发现相似商品哦~',
        stock: '库存不足',
        stock2: '库存',
        shop_verification: '请选择完整的商品规格！',
        add_success: '添加成功，在购物车等您哦~',
        confirm: '确认',
        num: '数量'
    },
    evaluate: {
        evaluate: {
            title: '评价',
            whole: '全部',
            Favorable_comments: '好评',
            Medium_evaluation: '中评',
            negative_comment: '差评',
            yes_img: '有图',
            Specifications: '规格',
            anonymous: '匿名',
            business_huifu: '商家回复',
            add_comments: '追加评论',
            unfold: "展开"
        },
        evaluating: {
            title: '发布评价',
            shop_pf: '商品评分',
            guige: '规格',
            evaluate_placeholder: '请输入您对该商品的评价……',
            add_img: '添加图片',
            upload_img: '上传图片',
            anonymous: '匿名发布',
            Submit: '提交',
            Submit_success: '提交成功',
            shop_evaluate: '请您为商品评价',
            Additional: '追加评价',
            Loading: '请稍后'
        },
        evaluatEnd: {
            title: '发布成功',
            return_home: '返回主页'
        }
    },
    expressage: {
        title: '物流信息',
        logistics_company: '物流公司',
        order: '物流单号',
        logistics_tips: '暂时还没有物流信息哦',
        copy: '复制',
        copy_success: '复制成功',
        no_copy: '无法复制文本',
        loading_fail: '数据加载失败！',
        Not_yet: '暂无物流信息',
    },
    goods: {
        goods: {
            Trade_name: '商品名称',
            subtitle: '子标题',
            sales_volume: '销量',
            shelf: '已下架',
            Sold_out: '已售罄',
            vip_price: '会员价',
            not: '暂时还没有本类商品哦',
            Insufficient_stock: '库存不足',
            Tips: '请选择完整的商品规格！',
            add_success: '添加成功，在购物车等您哦~',

        },
        goodsDet: {
            Bargaining_details: '砍价商品详情',
            rule: '砍价规则',
            vip_price: '会员价',
            sales: '销量',
            freight: '运费',
            Bargaining_success: '人已完成砍价',
            Collect_coupons: '领券',
            User_evaluation: '用户评价',
            No_evaluation: '暂无评价',
            sheets: '砍成晒单',
            share_shop: '分享店铺',
            Shop_in: '进店逛逛',
            Goods_sale: '在售商品',
            Sold: '已售',
            follow: '关注人数',
            Commodity_details: '商品详情',
            Trade_name: '商品名称',
            brand: '品牌',
            Commodity_number: '商品编号',
            classification: '分类',
            After_sale: '售后',
            qianshou: '签收之日起48小时内无条件退货',
            commodity_delete: '商品已经删除啦',
            shelf: '商品已经下架啦',
            soldOut: "商品已经卖完啦",
            close: '本店已打烊',
            customer_service: '客服',
            Collection: '收藏',
            Collected: '已收藏',
            add_cart: '加入购物车',
            Buy_now: '立即购买',
            end: '距砍价结束还剩',
            day: '天',
            Time: '时',
            branch: '分',
            second: '秒',
            More_bargains: '更多砍价商品',
            Bargain_now: '立即砍价',
            Continue_bargain: '继续砍价',
            Finished: '已结束',
            Not_started: '未开始',
            To_pay: '去付款',
            To_paid: '待付款',
            Paid: '已付款',
            Bargaining_failed: '砍价失败',
            Freight_rules: '运费规则',
            sales_volume: '销量',
            completed: '人已完成砍价',
            Save_picture: '保存图片',
            Invitation_link: '邀请链接',
            cancel: '取消',
            Copy_link: '复制链接',
            Share_with: '分享至',
            QR: '二维码分享',
            Wechat_friends: '微信好友',
            Wechat_circle: '微信朋友圈',
            free_shipping: '包邮',
            fracture: '折',
            Received: '已领取',
            lingqu: "立即领取",
            coupons: '暂无可领优惠券',
            Usage_rules: '使用规则',
            stock: '库存不足，无法参与砍价！',
            Save_success: '保存图片成功',
            fail_success: '保存图片失败',
            copy_success: '复制成功',
            Membership_level: '您的会员等级不满足购买要求，请升级会员等级后再购买!',
            distribution: '您的分销等级不满足购买要求，请升级分销等级后再购买!',
            no_vip: '对不起，你不是会员',
            shelf2: '该商品下架！',
            confirm: '确认',
            number: '数量',
            stock: '库存'
        }
    },
    index: {
        In: '秒后进入',
    },
    liveReplay: {
        Live_products: '直播商品',
        go_buy: '去购买',
        over: '播完了'
    },
    message: {
        title: '消息',
        share: '共有',
        Messages: '条信息',
        Yes: '有',
        Unread: '条未读',
        One_read: '一键已读',
        edit: '编辑',
        complete: '完成',
        System_message: '系统消息',
        View_details: '查看详情',
        no_message: '您还没有收到消息哦',
        Select_all: '全选',
        deletes: '删除',
        wantDel: "请选择需要删除的消息！",
        delSuc1: "成功删除",
        delSuc2: "条消息",
        noLogin: "未登录，请先登录",
        timeout: "账号登录超时,请重新登录！",
        failGet: "获取失败，请重试",
        nounread: "暂无未读消息"
    },
    service: {
        title: '在线客服'
    },
    detailed: {
        title: '系统信息'
    },
    aboutMe: {
        title: '关于我们'
    },
    gradeUse: {
        title: '使用说明'
    },
    myinfo: {
        title: '我的信息',
        Avatar_settings: '头像设置',
        My_nickname: '我的昵称',
        data: '出生日期',
        change: '请选择日期',
        modify_nickname: '修改昵称',
        cancel: '取消',
        determine: '确定',
        Tips: '提示',
        Tips_birthday: '生日只可以设置一次，是否确定修改？',
        nickname: ['昵称最长只能六位！', '昵称已存在，请重新输入！', '请输入昵称！'],
        upload_seccess: '上传成功'
    },
    allGoods: {
        title: '全部分类',
        no_goods: '暂时还没有二级分类哦'
    },
    home: {
        // search_placeholder: '搜索你想要的商品',
        // super_value: '超值拼团',
        group_people: '人已团',
        Spell_people: '人拼',
        shop: '优选店铺',
        position_user: '授权位置失败，请在系统设置中打开定位服务',
        got: '我知道了',
        shelf: '已下架',
        Sold_out: '已售罄',
        hot: '热销',
        recommend: '推荐',
        New_products: '新品',
        vip_price: '会员价',
        sales: '已售',
        Look: '找相似',
        piece: '件',
        access_to_locate: '获取定位',
        please_open_locate: '请打开定位，并授权应用位置权限！',
        more: '更多',
        noAvailable: "该功能暂未开放",
        openWeChat: "请在微信小程序打开",
        updateFail: "更新失败！",
        cancel:'取消',
        confirm:'确认',
        Tips:['请授权位置获取更好的体验','立即升级','更新内容','签到领积分','连续签到赢','大礼包','立即去签到'],
        nav_list: [
            '服饰',
            '鞋靴', 
            '箱包', 
            '百货', 
            '数码', 
            '电器', 
        //     '疯狂砍价', 
          
        //     '吉采直播', 
        
        //     '优选店铺', 
        //     '会员中心',
        ],
        title:'豪眼光'
    },
    order: {
        myorder: {
            title: '我的订单',
            order_placeholder: '请输入商品名称/订单号',
            search: '搜索',
            search_gjc: '请输入搜索关键词',
            whole: '全部',
            to_paid: '待付款',
            to_delivered: '待发货',
            to_Receiving: '待收货',
            to_evaluated: '待评价',
            no_order: '您还没有相关的订单哦',
            go_shopping: '去逛逛',
            shop_name: '店铺名称',
            common: '共',
            piece: '件',
            total: '合计',
            payment: '立即付款',
            deliver_goods: '提醒发货',
            deliver_goods2: '已提醒卖家发货',
            deliver_goods3: '请不要频繁点击提醒！',
            Confirm_receipt: '确定收货',
            return_goods: '退货',
            add_evaluation: '追加评价',
            Buy_again: '再次购买',
            Invite_friends: '邀请好友',
            cancel_order: '取消订单',
            View_Logistics: '查看物流',
            delete_order: '删除订单',
            View_details: '查看详情',
            Group_details: '拼团详情',
            cancel_success: '取消成功',
            loading: '数据加载失败！',
            prompt: '删除提示',
            prompt1: '取消提示',
            sure: '是否删除订单?',
            sure1: '是否取消订单?',
            delete_success: '删除成功',
            search_input: '请输入搜索关键词',
            Tips2: '请确认已收到货，否则您可能钱货两空',
            cancel: '取消',
            confirm: '确认',
            order_gb: '订单关闭，支付失败',
            transaction: '交易完成',
            Extraction:['查看提取码','提取码'],
            Tips: ['商品参数已变更，请重新购买！']
        },
        batchOrder: {
            title: '选择商品列表',
            Select_all: '全选',
            determine: '确定',
            Tips: '请选择需要售后的商品！'
        },
        order_pay: {
            title: '请选择支付方式',
            Tips: ['请稍等..', '正在请求支付...', '支付成功！']
        },
        orderSearch: {
            title: '搜索结果',
            loading: '加载中……',
            state: ['待付款', '待发货', '待收货', '交易成功', '交易关闭', '订单完成', '拼团失败', '拼团中'],
            Button: ['拼团', '砍价', '竞拍', '分销', '积分', '秒杀'],
            gift: '赠品',
            common: '共',
            piece: '件',
            total: '合计',
            Tips: '您还没有相关的订单哦',
            Go_shopping: '去逛逛',
            order_number: '订单编号',
            code: '验证码',
            Tips2: ['取消成功', '卖家已发货！', '数据加载失败！', '删除成功！', '收货成功！', '已提醒卖家发货']
        },
        order: {
            title: '订单详情',
            state: ['待付款', '已付款', '已发货', '交易成功', '交易关闭', '订单完成', '拼团失败', '拼团中'],
            logistics: ['物流信息', '物流信息: 该订单已拆分', '个包裹发出, 点击“查看物流”可查看详情', '暂无物流信息'],
            button: ['申请退款', '申请售后', '立即评价', '追加评论', '查看售后'],
            gift: '赠品',
            Reasons: '拒绝原因',
            total: '商品总价',
            Discount: ['店铺优惠金额', '优惠', '会员折扣优惠', '优惠券', '分销折扣', '会员等级折扣', '其他优惠'],
            fracture: '折',
            freight: '运费',
            Order_notes: '订单备注',
            order_total: '订单总价',
            Actual_payment: '实付款',
            order_number: '订单编号',
            Order_time: '下单时间',
            copy: '复制',
            button2: ['批量售后', '查看物流', '删除订单', '提醒发货'],
            common: '共',
            piece: '件',
            total2: '合计',
            code: '验证码',
            copy_success: '复制成功！',
            delete_success: '删除成功！',
            leftText: ['取消订单', '删除订单', '查看物流'],
            rightText: ['立即付款', '申请退货', '确认收货', '立即评价', '再次购买', '联系客服', '追加评价', '批量售后'],
            Order_timeout: '订单超时',
            order_cancel: '取消订单',
            Time:'时',
            branch:'分',
            second:'秒后订单关闭'
        }
    },
    pay: {
        orderDetailsr: {
            title: '确认订单信息',
            vip_price: '会员价',
            freight: '运费',
            Free_mail: '免邮',
            Clip_coupons: '使用优惠券',
            choose: '请选择店铺优惠',
            Order_notes: '订单备注',
            Subtotal: '小计',
            order_placeholder: '选填，请先和商家协商一致',
            reduction: '会员折扣减',
            Discount: ['平台优惠/满减活动', '请选择平台优惠', '使用优惠券', '满减优惠', '会员等级折扣', '分销等级购物折扣'],
            fracture: '折',
            total: '合计',
            close: '关闭',
            cannotCoupon: "不能使用该优惠券",
            Tips:['不使用优惠券',':优惠','元']
        },
        payResult: {
            title: '支付结果',
            Tips: '您的商品很快就会找您啦！',
            Order_number: '订单编号',
            Payment_amount: '支付金额',
            Continue_shopping: '继续购物',
            View_order: '查看订单',

        }
    },
    scavenging: {
        title: '码上购',
        search_tips: '殿下，此商品暂无销售，且试试关键字搜索吧',
        Commodity: '商品条码',
        Commodity_placeholder: '输入商品名称',
        Specifications: '规格',
        Loading: '加载中……'
    },
    livePlayer: {
        title: '吉采直播',
        live_broadcast: '直播人',
        no_data: '暂无直播数据',
        topBar: ['正在直播', '未开始', '已结束']
    },
    coupon: {
        title: '确认订单信息',
        Loading: '加载中',
        add_address: '点击添加地址',
        element: '元',
        Specifications: '规格',
        freight: '运费',
        free_shipping: '包邮',
        total: '合计',
        Balance: ['余额支付', '余额', '使用余额', '付款金额'],
        placeholder: '请输入抵扣金额',
        need_pay: '还需支付',
        payment: ['微信支付', '支付宝支付'],
        start_payment: ['立即支付', '立即兑换'],
        pay_pass: '请输入支付密码',
        forget_pass: '忘记密码',
        cancel: '取消',
        confirm: '确认',
        Tips: [
            '无支付密码，前往设置！', '请选择支付方式！', '创建订单失败,请稍后再试!',
            '支付成功！', '支付失败,查看订单详情', '提示', '请完善收货地址', '请先设置支付密码',
            '金额不足以支付商品价格!', '您已生成待付款订单，请前去支付', '正在请求支付...',
            '您输入密码错误,请重新输入', '你输入的错误次数已达当日上限，请使用其它支付方式进行付款',
            '网络错误，请稍后再试', '请输入完整密码！', '支付失败,订单已生成，可以在订单列表中查看',
            '网络繁忙 支付失败 订单已生成，可以在订单列表中查看', '已超过最大金额', '异常交易',
        ],
        set_up: '去设置',
    },
    expressageb: {
        title: '查看物流',
        logistics: '物流单号',
        Loading: '数据加载失败！'
    },
    chooseArea: {
        title: '选择收货地址',
        search: '搜索',
        search_placeholder: '请输入城市名称',
        current_location: '当前位置',
        change_address: '请选择地址',
        Switch: '切换区县'
    },
    mchList: {
        title: '优选店铺',
        Closed: '已打烊',
        sale: '在售商品',
        Sold: '已售',
        store:'进店',
        collectors: '收藏人数',
    },
    proList: {
        title1: "新品上市",
        title2: "好物优选",
        shelf: '已下架',
        vip_price: '会员价',
        Tips: ['库存不足', '请选择完整的商品规格！', '添加成功，在购物车等您哦~']
    },
    integral: {
        exchange: {
            title: '我的兑换',
            time: '兑换时间',
            Tips: ['您暂时还没有兑换的商品哦', '去逛逛'],
        },
        integral_detail: {
            title: '商品详情',
            market_value: '市场价',
            sales: '销量',
            share: '分享',
            User_evaluation: '用户评价',
            anonymous: '匿名',
            No_evaluation: '暂无评价',
            Share_shop: '分享店铺',
            Shop_in: '进店逛逛',
            sellingGoods: "在售商品",
            soldOut: "已售",
            followers: "关注人数",
            Commodity_details: '商品详情',
            Redeem_now: '立即兑换',
            shelf: '已下架',
            Save_picture: '保存图片',
            Share: '分享至',
            Wechat_friends: '微信好友',
            QR: '二维码分享',
            friends: '微信朋友圈',
            cancel: '取消',
            Tips: ['该活动已结束！', '保存图片成功', '保存图片失败', '复制分享链接成功！', '复制分享链接失败！', ]
        },
        integral_order: {
            title: '确认订单信息',
            freight: '运费',
            Commodity_amount: '商品金额',
            balance: '余额',
            Total_points: '积分总额',
            points: '积分',
            Free_mail: '免邮',
            total: '合计',
            Confirm_exchange: '确认兑换',
            Tips: [
                '兑换中...', '支付成功', '兑换失败，请重试！', '请完善收货地址！', '余额不足，无法兑换！',
                '积分不足，无法兑换！', '交易异常',
            ]
        },
        integral: {
            title: '积分商城',
            my_integral: '我的积分',
            Leading_integral: '领积分',
            Usage_rules: '使用规则',
            shelf: '已下架',
            Sold_out: '已售罄',
            market_value: '市场价',
            sales: '销量',
            Tips: ['暂无积分商品', ]
        }
    },
    //我的钱包
    myback: {
        title: '我的钱包',
        placeholder: '请输入账户名'
    },
    rechargeSucess: {
        title: '充值成功',
        text_p: "充值金额",
        card: "充值方式",
        back_wx: "微信支付",
        back_ali: "支付宝支付",
        title1: '提现申请',
        title_p1: "提现申请提交成功",
        text_p1: "提现金额",
        card1: "储蓄卡",
        Tips: '加速审核中，请耐心等待',
        tail: '尾号',
        Back_home: '返回首页',
        Back_wallet: '返回钱包',
        Back_shop: '返回店铺'
    },
    //我的秒杀
    seckill: {
        payResult: {
            title: '付款成功',
            Tips: '您的商品很快就会找您啦',
            Order_number: '订单编号',
            Payment_amount: '支付金额',
            shopping: '继续购物',
            View_order: '查看订单'
        },
        details: {
            title: '秒杀详情',
            Loading: '图片加载中…',
            limit: '限',
            piece: '件',
            Only: '仅剩',
            freight: '运费',
            User_evaluation: '用户评价',
            No_evaluation: '暂无评价',
            Share_shop: '分享店铺',
            Shop_in: '进店逛逛',
            sale: '在售商品',
            Sold: '已售',
            num: '关注人数',
            details: '商品详情',
            name: '商品名称',
            brand: '品牌',
            Commodity_number: '商品编号',
            classification: '分类',
            After_sale: '售后',
            start: '立即秒杀',
            Save_picture: '保存图片',
            Invitation_link: '邀请链接',
            copy_link: '复制链接',
            cancel: '取消',
            Share_with: '分享至',
            QR: '二维码分享',
            Wechat_friends: '微信好友',
            circle: '微信朋友圈',
            Button:['已结束','距结束','距开始'],
            button2:['即将开始','秒杀已结束','即将开抢'],
            Tips: [
                '签收之日起48小时内无条件退货', '库存不足，请选择其它!', '保存图片成功', '保存图片失败',
                '复制分享链接成功！', '复制分享链接失败！', '请先选择商品规格', '数量已经减少到最低了哦！',
                '超过最大库存!', '每人限购', '数量已经达到上限了哦！', '该商品已下架!', '活动已结束！',
                '活动未开始！', '账号登录超时,请重新登录！'
            ]
        },
        seckill_my: {
            title: '我的秒杀',
            status: ['待付款', '待发货', '待收货', '待评价', '交易关闭'],
            common: '共',
            piece: '件',
            total: '合计',
            button: ['取消订单', '立即付款', '提醒发货', '查看物流', '确认收货', '查看详情', '立即评价', '删除订单'],
            go_shoping: '去逛逛',
            Tips: ['您还没有相关的订单哦', '取消成功!', '取消失败!', '删除成功！', '已提醒卖家发货！', '收货成功', '数据加载失败！'],

        },
        seckill: {
            title: '限时秒杀',
            title2: '使用规则',
            ruel: '秒杀规则',
            Panic: ['抢购中', '即将开抢', '已结束', '立即抢购'],
            type: ['秒杀已结束', '抢购中，先抢先得', '即将开抢，先抢先得', '距结束', '距开始', '已抢光'],
            Robbed: '已抢',
            piece: '件',
            Tips: ['该时段暂无秒杀商品哦', '手速慢了哦，已经被抢完了！']
        }
    },
    setup2: {
        changePhone: {
            title: '修改手机号码',
            title1: '绑定手机号',
            phone_placeholder: '请输入有效的手机号码',
            code_placeHolder: '请输入手机验证码',
            obtain: '获取验证码',
            again: '后再次获取',
            confirm: '确认',
            Tips: ['新号码与旧号码一致！', '未获取到正确的手机号码！', '请填写完整信息！', '验证码错误！', '您输入的手机号码与原号码相同，请重新输入！', '修改成功！']
        },
        loginPass: {
            title: '修改登录密码',
            title2: '设置登录密码',
            code_placeHolder: '请输入手机验证码',
            obtain: '获取验证码',
            again: '后再次获取',
            pass_placeHolder: '请输入6-16位数的新密码',
            new_password: '请确认新密码',
            confirm: '确认',
            Back: '返回至个人中心',
            Tips: ['请输入6-15位数字或字母密码！', '两次输入不一致！', '请填写正确信息！', '请输入6-15位数字或字母密码！', '两次密码输入不一致！', '请输入正确的验证码！', '设置成功！', ]
        },
        payment: {
            title: '设置支付密码',
            code_placeHolder: '请输入手机验证码',
            obtain: '获取验证码',
            again: '后再次获取',
            pay_pass: '请输入6位支付密码',
            confirm_pass: '确认支付密码',
            confirm: '确认',
            Tips: ['请先绑定手机号码！', '未获取到正确的手机号码！', '支付密码全部由数字组成！', '两次密码输入不一致！', '请设置六位数密码！', '设置成功！', ]
        },
        paymentPass: {
            title: '修改支付密码',
            obtain: '获取验证码',
            again: '后再次获取',
            pay_pass: '请输入6位数新密码',
            confirm_pass: '请确认新密码',
            confirm: '确认',
            Tips: ['请先绑定手机号码！', '请输入6位数字密码', '两次密码输入不一致！', '请填写正确信息！', '请输入正确的验证码！', '修改成功！', ]
        }
    },
    vip: {
        title: '会员分享',
        preservation: '保存',
        Saved_successfully: '保存成功',
        vipRights:['全场','折','快速退货','活动专属','快速发货','其他优惠'],
        card:'月卡'
    },
    vipClub: {
        title: 'VIP会员中心',
        Member_sharing: '会员分享',
        upgrade: '升级',
        renew: '立即续费',
        Valid: '有效期至',
        interests: '我的专属权益',
        rules: '晋升规则',
        fracture: '折',
        Member_Specials: '会员特惠商品',
        member: '会员',
        member_price: '会员价',
        original: '原价',
        Wechat_friends: '微信好友',
        share: '分享',
        WeChat: '微信',
        Wechat_Moments: '朋友圈',
        QR: '二维码分享',
        Tips: ['复制分享链接成功！', '复制分享链接失败！', ],
        shareTitle: "会员推荐",
        shareSummary: "快来加入会员吧，享受更多优惠!"
    },
    vip2: {
        title: '豪眼光会员',
        Opening: '开通',
        savings: '预计最高可省',
        year: '元/年',
        exclusive: '专属',
        Enjoy: '开通即享全场商品',
        Discount: '折优惠',
        element: '元',
        interests: '会员权益',
        close: '关闭',
        ruel: '使用规则',
        cancel: '取消',
        confirm: '确认',
        settings: '去设置',
        click: '点击',
        Payment: ['支付方式', '微信支付', '支付宝支付', '百度支付', '余额支付'],
        button: ['开通', '续费', '升级', '立即开通', '立即续费', '立即升级'],
        privilege: ['会员特权', '享一季会员特权', '享一年会员特权'],
        card: ['月卡', '季卡', '年卡', '享一月'],
        Tips: ['按钮即代表已同意', '《豪眼光会员服务协议》', '无支付密码，前往设置！', '您已经是会员了', '支付失败！', '支付成功', '请输入完整密码！', ]
    },
    store: {
        title: '店铺主页',
        Closed: '已打烊',
        sale: '在售商品',
        Sold: '已售',
        num: '关注人数',
        people: '人收藏',
        piece: '件',
        Store_information: '查看门店信息',
        fracture: '折',
        receive: '领取',
        changeTab: ['推荐', '全部商品', '商品分类'],
        live_broadcast: '直播',
        playback: '回放',
        Watch_now: '立即观看',
        shelf: '已下架',
        member_price: '会员价',
        Save_picture: '保存图片',
        Share_with: '分享至',
        QR: '二维码分享',
        Wechat_friends: '微信好友',
        cancel: '取消',
        Tips: ['库存不足', '请选择完整的商品规格！', '添加成功，在购物车等您哦~', '领取成功', '保存图片成功', '保存图片失败', '复制成功！', ],
        toUse: '去使用',
        qiangguang: "已抢光"
    },
    shop: {
        coupon: {
            title: '领券中心',
            coupon: ['平台优惠券', '店铺优惠券', '去我的优惠券', '目前没有可以领取的优惠券哦'],
            fold: "折",
            Tips: ['领取成功', '未登录，请先登录'],
            points: ['立即领取', '已抢光', '去使用']
        },
        invite: {
            title: '邀请有奖',
            Loading: '加载中…',
            ruel: '活动规则',
            yuan: '元',
            got: '我知道了',
            invite: ['邀请攻略', '发送邀请给好友', '好友领取福利', '现金券到账'],
            Tips: [
                '每邀请一位新用户下单成功，奖励', '点击图片保存到本地',
                '保存成功', '保存失败，请稍后再试', '豪眼光分享', '网络繁忙，请稍后再试'
            ]
        },
        sign: {
            title: '每日签到',
            Loading: '加载中…',
            Current: '当前积分',
            ruel: '签到规则',
            day: '天',
            get: '获得',
            integral: '积分',
            Section: '第',
            second: '次',
            got: '我知道了',
            week: ['日', '一', '二', '三', '四', '五', '六'],
            Tips: ['已连续签到', '累计签到', '签到成功', '次签到获得', '今日还可签到', '今日签到已完成，请明日再来', '距离下次'],
            signIn: "点击签到",
            todaySigning: "今日已签",
            today: "今"
        }
    },
    search2: {
        search: {
            title: '搜索商品',
            title2: '搜索店铺',
            close: '关闭热门搜索',
            open: '开启热门搜索',
            search: '搜索',
            History: '历史搜索',
            Hot: '热门搜索',
            Tips: ['当前热门搜索已隐藏', '请输入搜索的名称', '记录清除成功','请输入商品名称']
        },
        searchRes: {
            title: '搜索结果',
            search_placeholder: '请输入你想搜索的内容',
            search_button: '搜索',
            TabBar: ['全部', '热销', '店铺'],
            TopButton: ['综合', '销量', '价格', '筛选', '品牌', '距离'],
            section: '价格区间（元）',
            min: '最低价',
            max: '最高价',
            Reset: '重置',
            determine: '确定',
            shelf: '已下架',
            Sold_out: '已售罄',
            member: '会员价',
            store: '进店',
            sale: '在售商品',
            Sold: '已售',
            num: '关注人数',
            Tips: [
                '没有找到', '的搜索结果', '您可以换个词再试试', '没有更多了', '添加成功，在购物车等您哦~',
                '库存不足', '请选择完整的商品规格！'
            ]
        }
    },
    refund: {
        title: '申请售后',
        amount: '退款金额',
        most: '最多',
        type: '售后类型',
        Return: '退换',
        r_status: ['退款说明', '申请原因', '退款', '售后', '退款信息', '售后信息'],
        upload: '上传凭证',
        input_placeholder: '最多200字',
        Upload3: '上传3张',
        Submit: '提交',
        Trade_name: '商品名称',
        order_number: '订单号',
        apply: '申请时间',
        amount_type: '退款类型',
        explain: '退款说明',
        refund_type: ['换货', '仅退款', '退货退款'],
        Tips: ['申请提交成功', '请耐心等待工作人员审核', '提交成功', '网络繁忙！', '请填写退款原因！', '请上传图片！', '字数已达到极限！', ]

    },
    returnGoods: {
        title: '请选择售后类型',
        only: '仅退款',
        Return_refund: '退货退款',
        exchange: '换货',
        Tips: ['未收到货，或与客服协商同意仅退款', '已收到货，需要退还已收到的货物', '确认收货，需要更换已收到的货物']
    },
    uploadPro: {
        title: '上传商品',
        title1: '编辑商品',
        title2: '商品详情',
        info: '基础信息',
        Product: '商品标题',
        Product_placeholder: [
            '请输入商品标题，1-20个字符', '请输入商品标题，1-14个字符',
            '请填写商品重量(单位：g/克)', '请填写商品条形码', '请选择商品主类名', '请选择商品品牌',
        ],
        Product_Vice: '商品副标题',
        keyword: '关键字',
        weight: '商品重量',
        code: '商品条形码',
        category: '商品类名',
        brand: '商品品牌',
        Exhibition: '展示图',
        cover: '封面图',
        set_graph: '设为主图',
        graph: '主图',
        attributes: '商品属性',
        price: ['成本价', '原价', '售价', '剩余库存', '库存预警', '单位', '设置属性'],
        inventory: '库存',
        price_placeholder: [
            '请设置商品的默认成本价', '请设置商品的默认原价',
            '请设置商品的默认售价', '请设置商品的默认库存', '请填写库存预警',
            '请设置商品的默认单位', '请设置商品的属性',
        ],
        set_up: ['商品设置', '运费设置', '显示标签', '支持活动', '显示位置', '等级绑定'],
        set_placeholder: ['请选择运费模板', '添加模板', '不绑定等级的会员商品'],
        Details: ['详细内容', '商品详情', '保存到本地', '提交审核'],
        Back: '返回',
        Tips: ['最多上传五张', '（建议尺寸为375*375）', '选择商品类别', '请选择商品类名！', '（建议500px，只在首页展示）'],
        freight: "运费",
        show_adr: "显示位置",
        choice:'选择',
        addFreight: "添加模板",
    },
    tixian: {
        title: '提现详情',
        money: '提现金额',
        s_charge: '提现手续费',
        Bank_card: '提现银行卡',
        add_date: '申请时间',
        refuse: '审核失败原因',
        examine_date: '审核时间',
        modify: '编辑',
        deletes: '删除',
        Reapply: '重新申请',
        Tips: ['审核中', '已完成', '审核失败，已退回账户']
    },
    storeSetup: {
        title: '店铺设置',
        setUp: '头像设置',
        shopName: '店铺名称',
        storeTitle: '店铺信息',
        storeRange: '经营范围',
        status: '营业状态',
        userName: '用户姓名',
        userID: '身份证号',
        userPhone: '联系电话',
        userAdd: '联系地址',
        cancellation: '店铺注销',
        cancel: '取消',
        confirm: '确定',
        Tips: [
            '修改店铺信息', '这里是店铺信息简单介绍', '修改经营范围', '这里是店铺经营范围简单介绍', '修改联系电话',
            '店铺注销后，将清空店铺', '所有信息且无法再次进入店铺', '是否确认注销', '修改成功', '修改失败', '请输入完整的信息',
            '请输入正确的电话号码','您的店铺拥有可提现余额','注销后将不能进行提取','请确认是否继续注销'
        ],
        businessArr: ['打烊','营业'],
    },
    storeRefund: {
        title: '退货审核',
        Return_type: ['退货类型', '退货退款', '退款', '换货'],
        refund_amount: '退款金额',
        Return_why: '退货原因',
        picture: '描述图片',
        cancel: '取消',
        confirm: '确定',
        refuse: '拒绝',
        adopt: '通过',
        Tips: [
            '确定要通过该用户的申请并让用户寄回', '请填写拒绝理由', '请输入拒绝理由',
            '请填写退款金额', '请输入退款金额', '应退', '确认后款项将原路返回', '已超过最大可退还金额',
            '操作成功', '拒绝成功', '退款成功',
        ]
    },
    storeList: {
        title: '门店列表',
        title2: '查看门店信息',
        edit: '编辑',
        address: '地址',
        Business_Hours: '营业时间',
        phone: '联系电话',
        Add_stores: '添加线下门店',
        Tips: ['加载中...', '请选择门店']
    },
    shipments: {
        title: '选择商品',
        title2: '填写物流信息',
        Select_all: '全选',
        deliver: '发货',
        express: ['快递公司', '请选择快递公司', '快递单号', '请填写快递单号'],
        determine: '确定',
        Tips: ['所有商品都已进入售后，无商品可发货！', '请选择发货商品', '加载中...', '发货成功', ]
    },
    setAttr: {
        title: '设置属性',
        title2: '选择属性名称',
        storage: '保存',
        Add_how: '添加方式',
        Attr: ['自定义属性名称', '属性名称', '请选择属性名称', '请选择属性值'],
        shop_Attr: ['请输入商品属性名称', '添加属性', '请输入商品属性值'],
        price: ['成本价', '原价', '售价', '库存'],
        add: '添加',
        deletes: '删除',
        complete: '完成',
        Tips: ['请填写属性名', '属性名已添加', '请填写属性值', '属性值已添加', '请选择属性名称', '请选择属性', '请添加属性']
    },
    seeCoupon: {
        title: '领取记录',
        receive: '领取',
        Zhang: '张',
        noRecord: '暂时还没有领取记录哦~'
    },
    QRsuccess: {
        title: '扫码提取',
        Validation: '验证成功',
        order_number: '订单编号',
        Payment: '支付成功',
        View_order: '查看订单',
        Back: '返回',
        Tips: ['商品自提成功']
    },
    QRdraw: {
        title: '验证码提取',
        QR: '验证码',
        QR_placeholder: '请输入提取验证码',
        verification: '验证',
        Tips: ['加载中', '请填写提货码']
    },
    QRcode: {
        // #ifndef MP-WEIXIN
        title: '验证方式',
        // #endif
        // #ifdef MP-WEIXIN
        title: '扫一扫',
        // #endif
        input: ['手动输入', '扫码输入'],
        Tips: ['加载中', 'H5不支持扫码功能，请选择手动输入']
    },
    platform: {
        title: '活动管理',
        group: '拼团',
        seckill: '秒杀',
        Activity: '活动时间',
        to: '至',
        type: ['未开始', '进行中', '已结束'],
        button: ['参与报名', '活动商品', '删除活动'],
        Tips: ['暂无活动信息']
    },
    mystore_order: {
        title: '订单详情',
        Loading: '加载中……',
        status: ['待付款', '待发货', '待收货', '已收货', '退货', '订单关闭', '订单完成'],
        order: '订单号',
        copy: '复制',
        order_time: '下单时间',
        Buyer: '买家',
        username: '收件人姓名',
        phone: '联系电话',
        address: '所在地区',
        address_placeholder: '请选择所在地区',
        addressinfo: '详细地址',
        Order_notes: '订单备注',
        Total: '商品总价',
        amount: ['店铺优惠金额', '优惠', '会员折扣优惠', '优惠券', '分销折扣', '会员等级折扣', '满减优惠'],
        fracture: '折',
        freight: '运费',
        Order_total: '订单总价',
        Paid_in: '实收款',
        edit: '编辑订单',
        View_Logistics: '查看物流',
        deliver: '发货',
        QR: '验证码核销',
        QRs: '自提扫码',
        complete: '完成',
        express: ['快递公司', '快递单号'],
        Submit: '提交',
        confirm: '确认',
        stock: '库存',
        Tips: ['填写物流信息', '请选择快递公司', '请填写快递单号', '库存不足，请选择其它!', '复制成功', '编辑订单', '加载中', 'H5不支持扫码功能，请选择手动输入']
    }
}
